# fly.toml app configuration file generated for benjaminclauss-protohackers on 2025-02-23T15:04:14-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'benjaminclauss-protohackers'
primary_region = 'ewr'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  protocol = "tcp"
  internal_port = 50001
  [[services.ports]]
    port = 50001

[[services]]
  protocol = "tcp"
  internal_port = 50002
  [[services.ports]]
    port = 50002

[[services]]
  protocol = "tcp"
  internal_port = 50003
  [[services.ports]]
    port = 50003

[[services]]
  protocol = "tcp"
  internal_port = 50004
  [[services.ports]]
    port = 50004

[[services]]
  protocol = "udp"
  internal_port = 50005
  [[services.ports]]
    port = 50005

[[services]]
  protocol = "tcp"
  internal_port = 50006
  [[services.ports]]
    port = 50006
